version: '3'

services:
  mvnbuild:
    build: ./mvnbuild
    restart: always
    volumes:
      - project_data:/tmp/project/target/

  tomcatweb:
    build: ./tomcatweb
    restart: always
    depends_on:
      - mvnbuild
    ports:
      - '8088:8080'
    volumes:
      - project_data:/usr/local/tomcat/webapps/

volumes:
  project_data: